name: client
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  imagebutton: ^0.0.6
  modal_bottom_sheet: ^2.0.0
  flutter_secure_storage: ^4.2.0
  image_picker: ^0.7.5+2
  provider: ^5.0.0
  image: ^2.1.4
  path_provider: ^2.0.2
  firebase_core: ^1.0.2
  firebase_storage: ^8.0.3
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/

